sudo: false
language: php
php:
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - rm composer.lock
  - travis_retry composer self-update
  - travis_retry composer install
script:
  - php --version
  - composer --version
  - composer check
